version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    entrypoint: celery
    command: -A app.celery.celery_app worker --loglevel=info
    env_file: .env
    links:
      - redis
    depends_on:
      - redis
      - db

  bot:
    build:
      context: ./telegram-bot/
    container_name: telegram_bot
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres_data: